### ISSUE TITLE
Widget sometimes does not react to touch

### ISSUE THREAD

**Issue by danielmmmm** [AChep/JellyBeanClock#1]
Sometimes the clock widget just doesn't do anything when I touch it. Moving the widget around still works. Maybe it has something to do with the size? The widget is 2x2, but since I do not have that much space, I resized it to 1x1.

**Comment by AChep** [comment]
https://github.com/AChep/JellyBeanClock/commit/76373a5f36e4748bf6ef05b5d644ecf6a5e7d0bf

**Comment by danielmmmm** [comment]
So the issue is fixed? Can we download the update with F-Droid? I tried several times, but I can only find the old version ...

**Comment by AChep** [comment]
Sorry, i'll rebuild as soon as i can

**Comment by danielmmmm** [comment]
Ah, cool! Thanks a lot! :-)

**Comment by AChep** [comment]
Updated

**Comment by danielmmmm** [comment]
I have tested your app for some days now and it seems to be fixed. Thanks a lot!
